Repository myteam-org/Webserv, pull requests merged in 2025-06, with the labels that each got.

#9 [REF] changed config class name
  Makefile
  compile_commands.json
  include/Config.hpp
  include/ConfigParser.hpp
  include/ConfigTokenizer.hpp
  include/ConfigTree.hpp
  src/config/Config.cpp
  src/config/ConfigParser.cpp
  src/config/ConfigTokenizer.cpp
  src/config/ConfigTree.cpp
  src/main.cpp
Labels: class

#14 13 feat location context class
  CMakeLists.txt
  Makefile
  config_file/default.conf
  include/Config.hpp
  include/ConfigParser.hpp
  include/ConfigTokenizer.hpp
  include/LocationContext.hpp
  include/ServerContext.hpp
  include/Token.hpp
  include/Validator.hpp
  include/data.hpp
  src/config/Config.cpp
  src/config/ConfigParser.cpp
  src/config/ConfigTokenizer.cpp
  src/config/LocationContext.cpp
  src/config/ServerContext.cpp
  src/main.cpp
  src/validator/Validator.cpp
  webserv
Labels: enhancement, class

#18 17 feat make document root config class
  Makefile
  include/DocumentRootConfig.hpp
  include/LocationContext.hpp
  include/ServerContext.hpp
  src/CMakeLists.txt
  src/config/Config.cpp
  src/config/ConfigParser.cpp
  src/config/DocumentRootConfig.cpp
  src/config/LocationContext.cpp
  webserv
Labels: enhancement, class

#34 21 feat value check config
  include/config/config.hpp
  include/config/context/location.hpp
  include/config/parser.hpp
  src/config/config.cpp
  src/config/parser.cpp
Labels: enhancement, class

#35 [33] feat: result<T>
  .clang-tidy
  .github/copilot-instructions.md
  .github/pull_request_template.md
  .github/pull_request_template.me
  include/utils/types/option.hpp
  include/utils/types/result.hpp
  test/CMakeLists.txt
  test/config/CMakeFiles/CMakeDirectoryInformation.cmake
  test/config/CMakeFiles/parser_test.dir/DependInfo.cmake
  test/config/CMakeFiles/parser_test.dir/build.make
  test/config/CMakeFiles/parser_test.dir/cmake_clean.cmake
  test/config/CMakeFiles/parser_test.dir/compiler_depend.make
  test/config/CMakeFiles/parser_test.dir/compiler_depend.ts
  test/config/CMakeFiles/parser_test.dir/depend.make
  test/config/CMakeFiles/parser_test.dir/flags.make
  test/config/CMakeFiles/parser_test.dir/link.txt
  test/config/CMakeFiles/parser_test.dir/parser_test.cpp.o.d
  test/config/CMakeFiles/parser_test.dir/progress.make
  test/config/CMakeFiles/progress.marks
  test/config/Makefile
  test/config/cmake_install.cmake
  test/config/parser_test
  test/config/parser_test[1]_include.cmake
  test/config/parser_test[1]_tests.cmake
  test/utils/CMakeLists.txt
  test/utils/types/CMakeLists.txt
  test/utils/types/option_test.cpp
  test/utils/types/result_test.cpp
Labels: class, type, result

#47 38 feat creat logger class
  .clang-tidy
  .github/copilot-instructions.md
  .gitignore
  include/utils/logger.hpp
  src/CMakeLists.txt
  src/utils/logger.cpp
Labels: class, log, utils

#52 50-bug add server_names & error_page default & index default
  config_file/default.conf
  include/config/config.hpp
  include/config/context/document_root.hpp
  include/config/context/location.hpp
  include/config/context/server.hpp
  include/config/parser.hpp
  include/config/token.hpp
  include/config/validator.hpp
  src/CMakeLists.txt
  src/config/config.cpp
  src/config/context/document_root.cpp
  src/config/context/server.cpp
  src/config/parser.cpp
  src/config/testPrint.cpp
  src/config/token.cpp
  src/config/validator.cpp
Labels: bug, class

#53 [39] feat: try macro
  include/utils/types/option.hpp
  include/utils/types/result.hpp
  include/utils/types/try.hpp
  test/utils/types/CMakeLists.txt
  test/utils/types/option_test.cpp
  test/utils/types/result_test.cpp
  test/utils/types/try_test.cpp
Labels: type, utils

#60 58 feat creat read class
  .clang-tidy
  include/io/input/read/buffer.hpp
  include/io/input/reader/fd.hpp
  include/io/input/reader/reader.hpp
  include/utils/types/error.hpp
  include/utils/types/result.hpp
  include/utils/types/try.hpp
  src/CMakeLists.txt
  src/io/input/read/buffer.cpp
  src/io/input/reader/fd.cpp
  test/CMakeLists.txt
  test/Testing/Temporary/CTestCostData.txt
  test/io/CMakeLists.txt
  test/io/input/CMakeLists.txt
  test/io/input/read/CMakeLists.txt
  test/io/input/read/buffer_test.cpp
  test/io/input/reader/CMakeLists.txt
  test/io/input/reader/fd_test.cpp
  test/test_template.cpp
Labels: class, read, I/O
